#!/bin/bash

# This is a bash script that uses the john tool to attempt to crack a password hash provided by the user. 

# Prompt user for password hash
#create a file with the hash as filename and as content
read -p "Enter password hash: " hash

# Use john to attempt to crack password hash
john --format=Raw-SHA256 --wordlist=/usr/share/wordlists/rockyou.txt --session=hash_crack $hash

# Display any cracked passwords
john --show --format=Raw-SHA256 --session=hash_crack
